### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-mpi#16]
11:- [ ] TODO: Open, what is mpi <https://github.com/cloudmesh/cloudmesh-mpi/issues/19>
- [x] ./doc/chapters/mpi.md:12:- [ ] TODO: Open, Ring <https://github.com/cloudmesh/cloudmesh-mpi/issues/15>
- [x] ./doc/chapters/mpi.md:13:- [ ] TODO: Open, calculation of pi <https://cvw.cac.cornell.edu/python/exercise>
- [x] ./doc/chapters/mpi.md:18:- [ ] TODO: Open, k-means there may be others <https://medium.com/@hyeamykim/parallel-k-means-from-scratch-2b297466fdcd>
- [x] ./doc/chapters/mpi.md:214:- [ ] TODO: Open, how to run it on multiple hosts on the PI
- [x] ./doc/chapters/mpi.md:238:- [ ] TODO: Open, VERIFY 
- [x] ./doc/chapters/mpi.md:254:- [ ] TODO: Open, learn about and evaluate and test if we can do 
- [x] ./doc/chapters/mpi.md:367:- [ ] TODO: Fidel, explenation is missing
- [x] ./doc/chapters/mpi.md:372:- [ ] TODO: All, add images
- [x] ./doc/chapters/mpi.md:399:- [ ] TODO: Fidel, explenation is missing
- [x] ./doc/chapters/mpi.md:431:- [ ] TODO: is there any difference should it be moved to bcast section?
- [x] ./doc/chapters/mpi.md:459:- [ ] TODO: is there any difference should it be moved to scatter section?
- [x] ./doc/chapters/mpi.md:492:- [ ] TODO: is there any difference should it be moved to gather section?
- [x] ./doc/chapters/mpi.md:566:- [ ] TODO, Fidel send recieve
- [ ] ./doc/chapters/mpi.md:634:- [ ] TODO: Cooper, spawn, pull
- [ ] ./doc/chapters/mpi.md:638:- [ ] TODO: Open, futures
- [x] ./doc/chapters/mpi.md:644:- [ ] TODO: Agnes, introduction
- [x] ./doc/chapters/mpi.md:648:- [ ] TODO: Agnes, MPI-IO
- [x] ./doc/chapters/mpi.md:652:- [ ] TODO: Agnes - IO and Numpy
- [x] ./doc/chapters/mpi.md:656:- [ ] TODO: Agnes, noncontigious IO
- [ ] ./doc/chapters/mpi.md:661:- [ ] TODO: Open, improve
- [x] ./doc/chapters/mpi.md:663:- [ ] TODO: Open  WHAT IS THE PROBLEM GOAL
- [x] ./doc/chapters/mpi.md:675:- [ ] TODO: Open, Drawing
- [x] ./doc/chapters/mpi.md:677:- [ ] TODO: Open, HOW AND WHY DO WE NEED MULTIPLE COMPUTERS
- [x] ./doc/chapters/mpi.md:681:- [ ] TODO: Open, PI Montecarlo
- [x] ./doc/chapters/mpi.md:684:- [ ] TODO: Open, Example program to run Montecarlo on multiple hosts
- [ ] ./doc/chapters/mpi.md:686:- [ ] TODO: Open, Benchmarking of the code
- [ ] ./doc/chapters/research.md:43:- [ ] TODO, All see other todos 
- [ ] ./doc/chapters/research.md:63:- [ ] TODO, Open,  Using Raspberry PIs
- [ ] ./doc/chapters/research.md:67:- [ ] TODO, Open, Laptops and Desktops
- [ ] ./doc/chapters/research.md:71:- [ ] TODO, Open, using vms
- [x] ./doc/chapters/research.md:77:- [ ] TODO: Erin, Using multipass
- [ ] ./doc/chapters/research.md:170:- [ ] TODO: Erin, campus resoources
- [ ] ./doc/chapters/research.md:179:- [ ] TODO: Erin, list resources hera nad how to get access
- [ ] ./doc/chapters/research.md:209:- [ ] TODO: Cooper, instalation on windows
- [ ] ./doc/chapters/research.md:213:- [ ] TODO: Agnes, instalation on Mac
- [ ] ./doc/chapters/research.md:217:- [ ] TODO: Open, using cms burn
- [ ] ./doc/chapters/research.md:221:- [ ] TODO: Open, using cms burn
- [ ] ./doc/chapters/wsl.md:33:- [ ] TODO: Cooper, how to start it the next time
- [ ] ./doc/chapters/dl.md:3:- [ ] TODO : Open, Install and use tensorflow
- [ ] ./doc/chapters/dl.md:4:- [ ] TODO : Open, Install and use horovod

**Comment by laszewsk** [comment]
This issue has been split up in various individual issues not not all checked of things are done, the may just refer to issues that have been converted
